name: Build & Code Quality Checks

on:
  pull_request:
    branches: ['main', 'develop']
    types: ['opened', 'reopened', 'synchronize']

permissions:
  contents: read

jobs:
  build:
    name: Build & Code Quality Checks
    runs-on: ubuntu-latest

    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@fa2e9d605c4eeb9fcad4c99c224cee0c6c7f3594 # v2.16.0
        with:
          egress-policy: audit

      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Setup Node
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'

      - name: Install dependencies
        env:
          HUSKY: 0
        run: |
          npm ci

      - name: Execute quality checks
        run: |
          npm run check:circular
          npm run check:duplicates

      - name: Execute security checks
        run: |
          npm run check:security
