name: Check PR title

on:
  pull_request:
    branches: ['main', 'develop']
    types: ['opened', 'reopened', 'edited', 'synchronize']

permissions:
  contents: read

jobs:
  check_pr_title:
    name: Check PR title
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@bf7454d06d71f1098171f2acdf0cd4708d7b5920 # v2.20.0
        with:
          egress-policy: audit

      - name: Checkout source branch
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Check PR title
        uses: rudderlabs/github-action-check-pr-title@e5718471c8eebd75c51a10ccce35f2cf33d18c04 # v1.0.12
